name: Build dashboard

on:
  push:
    branches: [ "main" ]

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis
        run: python run_analysis.py

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-outputs
          path: outputs/**
